### ISSUE TITLE
Exception when creating Auth Provider: Blender ID

### ISSUE THREAD

**Issue by fsiddi** [TaOuch/phabricator-blender-id-oauth-login#1]
When adding client id, secret and url, I get the following error once I press "Add Provider":

`Unhandled Exception ("AphrontQueryException")`
`#1048: Column 'providerDomain' cannot be null`

![Screenshot 2019-09-25 at 22 18 44](https://user-images.githubusercontent.com/451841/65636381-77619e80-dfe2-11e9-986f-4161de35ca86.png)

Does it happen with your configuration?

**Comment by TaOuch** [comment]
yes, it happens also .. i ll correct it this afternoon

**Comment by TaOuch** [comment]
i've pushed a fixe
